### ISSUE TITLE
Beam size of re-ranking model

### ISSUE THREAD

**Issue by Gitsamshi** [mitjanikolaus/compositional-image-captioning#1]
Hi there,
I have just read your paper regarding compositional generalization in image captioning. Very nice work, thanks! I have a small regarding the beam size for re-ranking, I didn't find this detail in the paper. May I know the beam size?

Also, may I know the full split information used as the upper bound in Table 2 (Full) of the paper.

**Comment by mitjanikolaus** [comment]
Hi, and thanks for your interest in our work!

The beam size used for re-ranking is B=100 (It's hidden in appendix E in the paper).

The upper bound (FULL) in Table 2 was calculated by training a model on a training set without any heldout pairs, i.e. the full COCO training data.

Hope this answers your questions!

**Comment by Gitsamshi** [comment]
Thank you for the quick response, may I know the detailed info for the full split, is it the karpathy split (113K, 5K, 5K) or the original split (83k, 35k, 5k)?

**Comment by mitjanikolaus** [comment]
We used the original split (82,783 images in the training set).

**Comment by Gitsamshi** [comment]
I see, thanks
